# Update these links to use your own Patreon/Liberapay/other
# crowdfunding links.

#github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: thepinsteam
#open_collective: # Replace with a single Open Collective username
#ko_fi: # Replace with a single Ko-fi username
#tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
#community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: AJHalili2006 # Replace with a single Liberapay username
#issuehunt: # Replace with a single IssueHunt username
#otechie: username
custom: [
   "https://donate.madebythepins.tk",
   "https://patreon.com/ajhalili2006"
]

