pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=Updated by Dependabot
    actions:
      review:
        type: APPROVE
        message: Approving @dependabot's pull request, merging...
      merge:
        method: merge
