version: 3

services:
    cdrs-starter-pack:
        image: "ghcr.io/code-server-boilerplates/starter-pack:cdr-latest"
        volumes:
            - code-server:/home/coder/project
        ports:
            - 8080:8080
        dns:
            # We're fans of Cloudflare DNS, so we'll use 1.1.1.1 for this one.
            # Prefer to use Google Public DNS? Replace these below.
            - 1.1.1.1
            - 1.0.0.1
        environment:
            - "GIT_REPO=https://github.com/code-server-boilerplates/charts"
            # Only uncomment this line below if you're on Okteto Cloud
            # going with Docker Compose.
            #- "PASSWORD=do-not-commit-your-secrets-plz"
            # Please see toolkits/containers/README.md for supported variables

volumes:
    code-server:
