name: "Docker CI (image releaser)"

env:
  # Change this to match GITHUB_REPOSITORY.
  # But please be reminded that Docker images only support
  # lowercased letters.
  repository: code-server-boilerplates/starter-pack

on:
  release:
    type: [published] # only trigger when an release is published

jobs:
  test:
     runs-on: "ubuntu-latest"
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"
       - name: Build image
         uses: docker/build-push-action@v2
         with:
           context: .
           platforms: linux/amd64,linux/arm64

  publish:
     needs: [ test ]
     runs-on: "ubuntu-latest"
     if: ${{ github.ref == 'refs/heads/main' && !github.event.issue.pull_request }}
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"

       # Setup QEMU for multiarch builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       # and of course, we need to setup Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"

       # repeat this for other registries you want to use
       # especially the official Docker Hub Registry
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           # change the username into yours if not using our bot
           username: RecapTimeBot
           # may not work on personal accounts if using our PAT
           # we may try soon
           password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
       - name: Login to Red Hat Quay Container Registry
         uses: docker/login-action@v1
         with:
           registry: quay.io
           # change the username into yours if not using our bot
           username: ${{ secrets.QUAYIO_USERNAME }}
           # may not work on personal accounts if using our PAT
           # we may try soon
           password: ${{ secrets.QUAYIO_PASSWORD }}

       # after building, we may retag them for DockerHub instead
       # of building again
       - name: Build and push to GHCR + DockerHub (amd64)
         id: image-build
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: |
             ghcr.io/${{ env.repository }}:stable
             quay.io/${{ env.repository }}:stable
             ghcr.io/${{ env.repository }}:latest
             quay.io/${{ env.repository }}:latest
             ghcr.io/${{ env.repository }}:${{ github.event.release.tag_name }}
             quay.io/${{ env.repository }}:${{ github.event.release.tag_name }}
           context: .
           platforms: linux/amd64,linux/arm64
       - name: Echo image digest
         run: echo Image digest is ${{ steps.image-build.outputs.digest }}
