name: "Image Test Builder for PRs"

on:
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2

       # Setup QEMU for multiarch builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       # and of course, we need to setup Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"

       # after building, we may retag them for DockerHub instead
       # of building again
       - name: Build image
         uses: docker/build-push-action@v2
         with:
           context: .
           platforms: linux/amd64,linux/arm64
