name: "Docker Builds CI (using official code-server images)"

on:
  push:
    branches: [ main ]
    paths:
      - "Dockerfile"
      - ".trigger-rebuild"
      - ".github/workflows/push-to-registry.yml"

jobs:
  test:
     #matrix:
       # archs supported by the official CDRS image
     #  arch: ["amd64", "arm64"]
     runs-on: "ubuntu-latest"
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"
       - name: Run tests
         run: docker build . --file Dockerfile
  publish:
     needs: [ test ]
     runs-on: "ubuntu-latest"
     if: ${{ github.ref == 'refs/heads/main' }}
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"

       # Setup QEMU for multiarch builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       # and of course, we need to setup Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"

       # repeat this for other registries you want to use
       # especially the official Docker Hub Registry
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           # change the username into yours if not using our bot
           username: RecapTimeBot
           # may not work on personal accounts if using our PAT
           # we may try soon
           password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}

       # after building, we may retag them for DockerHub instead
       # of building again
       - name: Build and push to GHCR + DockerHub (amd64)
         id: image-build
         uses: docker/build-push-action@v2
         with:
           push: true
           # version mapping:
           # - latest -> cdr-latest -> cdr-latest.debian10
           # - cdr-3.9.3 -> cdr.3.9.3.debian10
           tags: |
             ghcr.io/code-server-boilerplates/starter-pack:cdr-latest
             ghcr.io/code-server-boilerplates/starter-pack:cdr-latest.debian-10
             ghcr.io/code-server-boilerplates/starter-pack:latest
             ghcr.io/code-server-boilerplates/starter-pack:cdr-3.10.0
             ghcr.io/code-server-boilerplates/starter-pack:cdr-3.10.debian-10
           context: .
           platforms: linux/amd64,linux/arm64
       - name: Echo image digest
         run: echo ${{ steps.image-build.outputs.digest }}
