name: "Docker Builds CI"

on:
  push:
    branches: [ main ]

jobs:
  test:
     #matrix:
       # archs supported by the official CDRS image
     #  arch: ["amd64", "arm64"]
     runs-on: "ubuntu-latest"
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"
       - name: Run tests
         run: docker build . --file Dockerfile
  publish:
     needs: [ test ]
     runs-on: "ubuntu-latest"
     if: ${{ github.ref == 'refs/heads/main' }}
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"

       # Setup QEMU for multiarch builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1

       # repeat this for other registries you want to use
       # especially the official Docker Hub Registry
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
          registry: ghcr.io
          # change the username into yours if not using our bot
          username: RecapTimeBot
          # may not work on personal accounts if using our PAT
          # we may try soon
          password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}

       # after building, we may retag them for DockerHub instead
       # of building again
       - name: Build and push to GHCR
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: "ghcr.io/code-server-boilerplates/starter-pack"           context: .
           platforms: linux/amd64,linux/arm64

       - name: Echo image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
       - name: Check built images
         run: docker images | grep "code-server-boilerplates" || true
